### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by SzotsGabor** [kfeske/Priessnitz#1]
Hello Kevin,

I suggest to include version number in UCI id and, possibly, in file name as well, to avoid future confusion.

Gabor Szots
CCRL testing group

**Comment by kfeske** [comment]
Hello Gabor,

thanks for the advice!
I will definitely make these changes in future versions.

The binary files have also been updated and they seem to be working way
better now.
Previously, the windows version was a lot weaker.

Cheers
Kevin

Am Do., 26. Sept. 2024 um 07:59 Uhr schrieb Gabor Szots <
***@***.***>:
